typography_spectrum: 0.17625997601482687
color:
  brandStrength: 0.6329350225928949
  lightness: 0.8524402175435224
  saturation: 0.9043259008630815
  rhythmicContrast: 0.6409649340293859
  brandColors:
    - '#E0BE98'
    - '#B05DE8'
    - '#070707'
    - '#C8BFC7'
    - '#080808'
github: true
layout_spectrum: 0.01776697023043243
analytics:
  facebook: '999007766816091'
  google: UA-17071199-1
author:
  name: Gretchen Oris-Chong
  email: hello@eightcorners.co
  url: 'http://eightcorners.co'
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/5cd473aa-bc4f-4ce5-bf81-a6db6c678df5.png
name: eight corners blog
url: 'https://blog.eightcorners.co'
navigation:
  - name: home
    url: 'https://eightcorners.co'
    type: external
  - name: shop
    url: 'https://www.etsy.com/au/shop/eightcornerscreative'
    type: external
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/bb40f0ae-50da-405d-a939-ee1c7e264f5a.png
title: CREATERATI
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/8361d4fa-b89d-4fd4-aee9-10e3d1ed75aa.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/8361d4fa-b89d-4fd4-aee9-10e3d1ed75aa.jpg
    metadata:
      author: []
      related: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      keywords: []
      description: ''
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/244b7075-d299-4818-b8e0-2c4c1ed9ad48.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/244b7075-d299-4818-b8e0-2c4c1ed9ad48.jpg
    metadata:
      author: []
      related: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      keywords: []
      description: ''
      inLanguage: !<tag:yaml.org,2002:js/undefined> ''
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
description: A creative movement for game-changing entrepreneurs & explorers.
purpose:
  - type: external
    url: 'https://paperform.co/form/appealing-brand'
    label: 'FREE Cheatsheet: 8 Simple Steps to An Appealing Brand'
  - type: external
    url: 'https://www.etsy.com/au/shop/eightcornerscreative'
    label: Shop Templates
