typography_spectrum: 0.1815247831084203
color:
  brandStrength: 0.41642575880992083
  lightness: 0.9732196856002406
  saturation: 0.25520486706213125
  rhythmicContrast: 0.06140294846202625
  brandColors:
    - '#29044D'
    - '#E1BD9C'
    - '#C8BFC6'
    - '#735CBA'
    - '#070707'
github: true
layout_spectrum: 1
analytics:
  facebook: '999007766816091'
  google: UA-17071199-1
author:
  name: Gretchen Oris-Chong
  email: hello@eightcorners.co
  url: 'http://eightcorners.co'
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/5cd473aa-bc4f-4ce5-bf81-a6db6c678df5.png
name: eight corners blog
url: 'https://blog.eightcorners.co'
navigation:
  - name: HOME
    url: 'https://eightcorners.co'
    type: external
  - name: SHOP ebook templates
    url: 'http://shop.createrati.com'
    type: external
  - name: DIY your own design
    url: 'http://gretcho.link/ecourses'
    type: external
  - name: GET design clients
    url: 'http://gretcho.link/closingscript'
    type: external
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/bb40f0ae-50da-405d-a939-ee1c7e264f5a.png
title: CREATERATI
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/2fabf300-d35d-42ba-9373-0d86e297cf52.png">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/2fabf300-d35d-42ba-9373-0d86e297cf52.png
    metadata:
      datePublished: null
      keywords: []
      related: []
      author: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      app_links: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      description: ''
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/a7655c91-1cb9-428b-8c17-676388ac16e5.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/a7655c91-1cb9-428b-8c17-676388ac16e5.jpg
    metadata:
      datePublished: null
      keywords: []
      related: []
      author: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      app_links: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      description: ''
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
description: A creative movement for game-changing entrepreneurs & explorers.
purpose:
  - type: external
    url: 'http://gretcho.link/getkit'
    label: Get The STANDOUT BRAND + BIZ Toolkit
  - type: external
    url: 'http://thebrandtour.com'
    label: Join me on The Brand Tour
opengraph:
  appId: '1276522442415841'
  type: website
